import type { NativeAdapter, NativeEnvironment } from "@bunaway/plugin";
import type { PermissionMatcher } from "@bunaway/protocol";
import type { ManifestPlugin } from "@bunaway/runtime-bun/app-manifest";

export type { NativeAdapter, NativeEnvironment };

/** A plugin's installed contract and the factories available to each Windows worker. */
export type PackagedPlugin = Omit<ManifestPlugin, "authorization"> & {
  /** Lazily load permission-scope matching for registered scoped permissions. */
  authorization?: () => Promise<{
    matches: PermissionMatcher;
  }>;
  /** Lazily load the platform adapter after registration and worker selection. */
  operations?: () => Promise<{
    createOperations(environment: NativeEnvironment): NativeAdapter;
  }>;
};

/** Lazy imports generated by the CLI, keyed by the installed plugin name. */
export type PluginImports = Record<
  string,
  Pick<PackagedPlugin, "authorization" | "operations">
>;
