import type {
  NativeAdapter,
  NativeEnvironment,
} from "../../../packages/plugin-sdk/src/index.ts";
import type { PermissionMatcher } from "../../../packages/protocol/src/index.ts";
import type { ManifestPlugin } from "../../../packages/runtime-bun/src/app-manifest.ts";

export type { NativeAdapter, NativeEnvironment };

/** A plugin's installed contract and the factories available to each Windows worker. */
export type PackagedPlugin = Omit<ManifestPlugin, "authorization"> & {
  /** Lazily load permission-scope matching for registered scoped permissions. */
  authorization?: () => Promise<{
    matches: PermissionMatcher;
  }>;
  /** Lazily load the platform adapter after registration and worker selection. */
  operations?: () => Promise<{
    createOperations(environment: NativeEnvironment): NativeAdapter;
  }>;
};

/** Lazy imports generated by the CLI, keyed by the installed plugin name. */
export type PluginImports = Record<
  string,
  Pick<PackagedPlugin, "authorization" | "operations">
>;
