import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CODES, type StageContext } from "../../contract.ts";
import { findIscc, findWindowsKitTool, must, stableGuid } from "./common.ts";
import { signingArgs } from "./sign.ts";

// Inno Setup installer generation shared by win-direct and
// win-store-unpackaged. The script encodes the channel's install contract:
// install location by scope, WebView2 handling (check-only or bundled
// bootstrapper), shortcuts, per-user data preservation on uninstall, and
// over-install updates keyed by a stable AppId GUID.

export interface InnoOptions {
  name: string;
  identifier: string;
  appId?: string;
  version: string;
  publisher: string;
  scope: "perUser" | "perMachine";
  payloadDir: string;
  outputDir: string;
  outputBaseName: string;
  iconFile?: string;
  desktopShortcut: boolean;
  startMenuShortcut: boolean;
  webView2: "check" | "bootstrap";
  // Absolute path to Microsoft's Evergreen bootstrapper; only valid for
  // webView2="bootstrap". Store EXE/MSI submissions must be standalone and
  // never download at install time.
  bootstrapperPath?: string;
  // Absolute data root the host writes to; kept on uninstall unless the
  // channel config opts out (uninstall.preserveUserData=false).
  appDataDir: string;
  preserveUserData: boolean;
  assetPaths: string[];
  executableName?: string;
  signed?: boolean;
  minVersion?: string;
}

function issLiteral(value: string, constants = true): string {
  if (/[\r\n\0]/.test(value)) {
    throw new Error("Inno values must not contain line breaks or NUL.");
  }
  return constants ? value.replace(/{/g, "{{") : value;
}

function issParameter(value: string, constants = true): string {
  return issLiteral(value, constants).replace(/"/g, '""');
}

// Display names can contain characters forbidden in Windows directory names.
export function installerDirectoryName(name: string): string {
  return (
    // biome-ignore lint/suspicious/noControlCharactersInRegex: Windows forbids these characters in file names.
    name.replace(/[<>:"/\\|?*\x00-\x1f]/g, "_").replace(/[. ]+$/, "") || "App"
  );
}

export function renderInnoScript(options: InnoOptions): string {
  if (/^unins\d+\.exe$/i.test(options.executableName ?? "")) {
    throw new Error(
      "GUI executable name conflicts with the Inno uninstaller (uninsNNN.exe).",
    );
  }
  const minVersion = options.minVersion ?? "10.0.17763.0";
  if (!/^\d+\.\d+(?:\.\d+)?(?:\.0)?$/.test(minVersion)) {
    throw new Error("Windows minVersion must be major.minor[.build[.0]].");
  }
  const parts = minVersion.split(".").map(Number);
  if (
    parts.some((part) => part > 65535) ||
    (parts[0] ?? 0) < 10 ||
    (parts[0] === 10 && parts[1] === 0 && (parts[2] ?? 0) < 17763)
  ) {
    throw new Error(
      "Windows minVersion must be >= 10.0.17763.0 (bundled Bun requirement).",
    );
  }
  const perUser = options.scope === "perUser";
  if (!perUser && !options.preserveUserData) {
    throw new Error(
      "perMachine installs must preserve user data; cleanup requires a perUser install.",
    );
  }
  const shortcutName = installerDirectoryName(options.name);
  const directoryName = issLiteral(shortcutName);
  const identifier = issLiteral(options.identifier);
  const executableName = options.executableName ?? `${options.identifier}.exe`;
  const executable = issParameter(executableName);
  const executableLiteral = issLiteral(executableName, false).replace(
    /'/g,
    "''",
  );
  const appId = issParameter(options.appId ?? options.identifier);
  const menuLink = `{group}\\${directoryName}.lnk`;
  const uninstallLink = `{group}\\${directoryName} 제거.lnk`;
  const desktopLink = `{autodesktop}\\${directoryName} (${identifier}).lnk`;
  const shortcutCheck = (path: string) =>
    `; Flags: uninsneveruninstall; Check: ShouldCreateShortcut('${path.replace(/'/g, "''")}')`;
  const defaultDir = perUser
    ? `{localappdata}\\Programs\\${identifier}`
    : `{autopf}\\${identifier}`;
  const lines: string[] = [
    "; Generated by @bunaway/packaging. Do not edit.",
    "[Setup]",
    `AppId={{${stableGuid(options.identifier)}}}`,
    `AppName=${issLiteral(options.name)}`,
    `AppVerName=${issLiteral(options.name)} ${options.version}`,
    `AppVersion=${options.version}`,
    `AppPublisher=${issLiteral(options.publisher)}`,
    `DefaultDirName=${defaultDir}`,
    `DefaultGroupName=${identifier}`,
    "WizardStyle=modern",
    "Compression=lzma2",
    "SolidCompression=yes",
    "ArchitecturesAllowed=x64compatible",
    "ArchitecturesInstallIn64BitMode=x64compatible",
    // Inno uses three parts; the optional MSIX-style revision must be zero.
    `MinVersion=${parts.slice(0, 3).join(".")}`,
    "CloseApplications=yes",
    // Each installer is a complete snapshot; old data-deletion records must
    // not override the current uninstall policy.
    "UninstallLogMode=overwrite",
    `UninstallDisplayIcon={app}\\${executable}`,
    `OutputDir=${options.outputDir}`,
    `OutputBaseFilename=${options.outputBaseName}`,
    perUser ? "PrivilegesRequired=lowest" : "PrivilegesRequired=admin",
  ];
  if (options.signed) {
    lines.push(
      "SignTool=bunaway",
      "SignedUninstaller=yes",
      `SignedUninstallerDir=${join(options.outputDir, "..", "inno-signing")}`,
    );
  }
  if (options.iconFile) {
    lines.push(`SetupIconFile=${options.iconFile}`);
  }

  lines.push("", "[Files]");
  lines.push(
    `Source: "${issParameter(options.payloadDir, false)}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs`,
  );
  if (options.bootstrapperPath) {
    lines.push(
      `Source: "${issParameter(options.bootstrapperPath, false)}"; DestDir: "{tmp}"; DestName: "MicrosoftEdgeWebview2Setup.exe"; Flags: dontcopy`,
    );
  }

  if (options.desktopShortcut) {
    lines.push(
      "",
      "[Tasks]",
      `Name: "desktopicon"; Description: "${issParameter(`${options.name} 바로가기 만들기`)}"; GroupDescription: "바로가기:"`,
    );
  }
  if (options.startMenuShortcut || options.desktopShortcut) {
    lines.push("", "[Icons]");
    if (options.startMenuShortcut) {
      lines.push(
        `Name: "{group}\\${directoryName}"; Filename: "{app}\\${executable}"; WorkingDir: "{app}"; IconFilename: "{app}\\${executable}"; AppUserModelID: "${appId}"${shortcutCheck(menuLink)}`,
      );
      lines.push(
        `Name: "{group}\\${directoryName} 제거"; Filename: "{uninstallexe}"${shortcutCheck(uninstallLink)}`,
      );
    }
    if (options.desktopShortcut) {
      lines.push(
        `Name: "{autodesktop}\\${directoryName} (${identifier})"; Filename: "{app}\\${executable}"; WorkingDir: "{app}"; IconFilename: "{app}\\${executable}"; AppUserModelID: "${appId}"; Tasks: desktopicon${shortcutCheck(desktopLink)}`,
      );
    }
  }

  const runEntries: string[] = [];
  runEntries.push(
    `Filename: "{app}\\${executable}"; WorkingDir: "{app}"; Description: "${issParameter(`Launch ${options.name}`)}"; Flags: postinstall nowait skipifsilent unchecked`,
  );
  if (runEntries.length) {
    lines.push("", "[Run]", ...runEntries);
  }

  if (!options.preserveUserData) {
    lines.push(
      "",
      "[UninstallDelete]",
      `Type: filesandordirs; Name: "${options.appDataDir}"`,
    );
  }

  lines.push(
    "",
    "[Code]",
    "var PreviousExecutableName: String;",
    "    PreviousInstallDir: String;",
    "",
    "function IsSafeExecutableName(const Name: String): Boolean;",
    "var I: Integer;",
    "begin",
    "  Result := False;",
    "  if Name = '' then Exit;",
    "  if CompareText(ExtractFileExt(Name), '.exe') <> 0 then Exit;",
    "  if (Name[Length(Name)] = '.') or (Name[Length(Name)] = ' ') then Exit;",
    "  for I := 1 to Length(Name) do",
    "    if (Ord(Name[I]) < 32) or (Name[I] = '<') or (Name[I] = '>') or",
    "       (Name[I] = ':') or (Name[I] = '\"') or (Name[I] = '/') or",
    "       (Name[I] = '\\') or (Name[I] = '|') or (Name[I] = '?') or",
    "       (Name[I] = '*') then Exit;",
    "  Result := True;",
    "end;",
    "",
    "function HasRuntimeVersion(const Version: String): Boolean;",
    "var PackedVersion: Int64;",
    "begin",
    "  Result := False;",
    "  if StrToVersion(Version, PackedVersion) then",
    "    Result := ComparePackedVersion(PackedVersion, 0) > 0;",
    "end;",
    "",
    "// Evergreen WebView2 runtime presence check (Microsoft-documented GUID).",
    "function HasWebView2Runtime: Boolean;",
    "var Version: String;",
    "begin",
    "  Result := RegQueryStringValue(HKLM, 'SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
    "  if not Result then",
    "    Result := RegQueryStringValue(HKLM, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
    ...(perUser
      ? [
          "  if not Result then",
          "    Result := RegQueryStringValue(HKCU, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
        ]
      : []),
    "end;",
    "",
  );
  if (options.bootstrapperPath) {
    lines.push(
      "function PrepareToInstall(var NeedsRestart: Boolean): String;",
      "var ResultCode: Integer;",
      "begin",
      "  Result := '';",
      "  if HasWebView2Runtime then Exit;",
      "  ExtractTemporaryFile('MicrosoftEdgeWebview2Setup.exe');",
      "  if not Exec(ExpandConstant('{tmp}\\MicrosoftEdgeWebview2Setup.exe'), '/silent /install', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then",
      "    Result := 'Could not start the WebView2 Runtime installer: ' + SysErrorMessage(ResultCode)",
      "  else if ResultCode <> 0 then",
      "    Result := 'WebView2 Runtime installation failed (exit code ' + IntToStr(ResultCode) + '). Check your internet connection and retry.'",
      "  else if not HasWebView2Runtime then",
      "    Result := 'WebView2 Runtime was not detected after installation. Install the runtime and retry.';",
      "end;",
      "",
    );
  }
  lines.push(
    "procedure RemovePreviousExecutable;",
    "var Path: String; Entry: TFindRec;",
    "begin",
    "  if (PreviousExecutableName = '') or",
    `     (CompareText(PreviousExecutableName, '${executableLiteral}') = 0) then Exit;`,
    "  Path := ExpandConstant('{app}') + '\\' + PreviousExecutableName;",
    "  if CompareText(Path, ExpandConstant('{uninstallexe}')) = 0 then Exit;",
    "  if not FindFirst(Path, Entry) then Exit;",
    "  try",
    "    if ((Entry.Attributes and (FILE_ATTRIBUTE_DIRECTORY or FILE_ATTRIBUTE_REPARSE_POINT)) = 0) and",
    "       not DeleteFile(Path) then",
    "      RaiseException('Could not remove previous app executable: ' + Path);",
    "  finally",
    "    FindClose(Entry);",
    "  end;",
    "end;",
    "",
    String.raw`// Inspect only the configured path. Never search for renamed or moved links.
function ReadShortcut(const Filename: String; var Link: Variant; var Target: String): Boolean;
var Shell, Folder, Item: Variant; Entry: TFindRec;
begin
  Result := False;
  Target := '';
  if not FindFirst(ExtractFileDir(Filename), Entry) then Exit;
  try
    if (Entry.Attributes and FILE_ATTRIBUTE_REPARSE_POINT) <> 0 then Exit;
  finally FindClose(Entry); end;
  if not FindFirst(Filename, Entry) then Exit;
  try
    if (Entry.Attributes and (FILE_ATTRIBUTE_DIRECTORY or FILE_ATTRIBUTE_REPARSE_POINT)) <> 0 then Exit;
  finally FindClose(Entry); end;
  try
    // Shell.Application preserves Unicode paths that WScript.Shell can lose via ANSI conversion.
    Shell := CreateOleObject('Shell.Application');
    Folder := Shell.Namespace(ExtractFileDir(Filename));
    Item := Folder.ParseName(ExtractFileName(Filename));
    Link := Item.GetLink;
    Target := Link.Path;
    Result := True;
  except Log('Could not inspect shortcut: ' + Filename); end;
end;

function ShouldCreateShortcut(const Filename: String): Boolean;
var Entry: TFindRec;
begin
  Result := not FindFirst(ExpandConstant(Filename), Entry);
  if not Result then FindClose(Entry);
end;

procedure UpdateShortcut(const Filename: String);
var Link: Variant; Target, Arguments: String;
begin
  if (PreviousExecutableName = '') or
     (CompareText(PreviousExecutableName, '${executableLiteral}') = 0) or
     (CompareText(AddBackslash(PreviousInstallDir), AddBackslash(ExpandConstant('{app}'))) <> 0) then Exit;
  if not ReadShortcut(Filename, Link, Target) then Exit;
  if CompareText(Target, ExpandConstant('{app}') + '\' + PreviousExecutableName) <> 0 then Exit;
  try Arguments := Link.Arguments;
  except Log('Could not inspect shortcut arguments: ' + Filename); Exit; end;
  Link.Path := ExpandConstant('{app}') + '\' + '${executableLiteral}';
  Link.Arguments := Arguments;
  Link.Save(Filename);
end;

procedure DeleteShortcut(const Filename, ExpectedTarget: String);
var Link: Variant; Target: String;
begin
  if not ReadShortcut(Filename, Link, Target) then Exit;
  if CompareText(Target, ExpectedTarget) <> 0 then Exit;
  if not DeleteFile(Filename) then Log('Could not remove shortcut: ' + Filename);
end;
`,
    "procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);",
    "begin",
    "  if CurUninstallStep <> usUninstall then Exit;",
    ...[
      menuLink,
      desktopLink,
    ].map(
      (path) =>
        `  DeleteShortcut(ExpandConstant('${path.replace(/'/g, "''")}'), ExpandConstant('{app}') + '\\' + '${executableLiteral}');`,
    ),
    `  DeleteShortcut(ExpandConstant('${uninstallLink.replace(/'/g, "''")}'), ExpandConstant('{uninstallexe}'));`,
    "end;",
    "",
    "procedure PruneAssets(const Base, Relative: String; Current: TStringList);",
    "var Entry: TFindRec; Path, Child: String;",
    "begin",
    "  Path := Base + '\\' + Relative;",
    "  if not FindFirst(Path, Entry) then Exit;",
    "  try",
    "    if (Entry.Attributes and FILE_ATTRIBUTE_REPARSE_POINT) <> 0 then Exit;",
    "  finally",
    "    FindClose(Entry);",
    "  end;",
    "  if FindFirst(Path + '\\*', Entry) then begin",
    "    try",
    "      repeat",
    "        if (Entry.Name <> '.') and (Entry.Name <> '..') and",
    "           ((Entry.Attributes and FILE_ATTRIBUTE_REPARSE_POINT) = 0) then begin",
    "          Child := Relative + '\\' + Entry.Name;",
    "          if (Entry.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then begin",
    "            PruneAssets(Base, Child, Current);",
    "            RemoveDir(Base + '\\' + Child);",
    "          end else if Current.IndexOf(Child) < 0 then begin",
    "            if not DeleteFile(Base + '\\' + Child) then",
    "              Log('Could not remove obsolete asset: ' + Child);",
    "          end;",
    "        end;",
    "      until not FindNext(Entry);",
    "    finally",
    "      FindClose(Entry);",
    "    end;",
    "  end;",
    "end;",
    "",
    "procedure CurStepChanged(CurStep: TSetupStep);",
    "var Current: TStringList;",
    "begin",
    "  if CurStep <> ssPostInstall then Exit;",
    "  if (PreviousExecutableName = '') or (PreviousInstallDir = '') or",
    "     (CompareText(AddBackslash(PreviousInstallDir), AddBackslash(ExpandConstant('{app}'))) <> 0) then",
    "    PreviousExecutableName := '';",
    "  Current := TStringList.Create;",
    "  try",
    "    Current.CaseSensitive := False;",
    "    Current.Sorted := True;",
    ...options.assetPaths.map(
      (path) =>
        `    Current.Add('${issLiteral(path, false).replace(/\//g, "\\").replace(/'/g, "''")}');`,
    ),
    "    PruneAssets(ExpandConstant('{app}'), 'licenses', Current);",
    ...[
      menuLink,
      desktopLink,
    ].map(
      (path) =>
        `    UpdateShortcut(ExpandConstant('${path.replace(/'/g, "''")}'));`,
    ),
    "    RemovePreviousExecutable;",
    "  finally",
    "    Current.Free;",
    "  end;",
    "end;",
    "",
  );
  lines.push(
    "procedure RegisterExtraCloseApplicationsResources;",
    "begin",
    "  if (PreviousExecutableName <> '') and (PreviousInstallDir <> '') and",
    `     (CompareText(PreviousExecutableName, '${executableLiteral}') <> 0) and`,
    "     (CompareText(AddBackslash(PreviousInstallDir), AddBackslash(ExpandConstant('{app}'))) = 0) and",
    "     FileExists(ExpandConstant('{app}') + '\\' + PreviousExecutableName) then",
    "    if not RegisterExtraCloseApplicationsResource(True, ExpandConstant('{app}') + '\\' + PreviousExecutableName) then",
    "      RaiseException('Could not check the previous app executable for running applications.');",
    "end;",
    "",
    "function InitializeSetup: Boolean;",
    "begin",
    "  PreviousExecutableName := GetPreviousData('ExecutableName', '');",
    "  if not IsSafeExecutableName(PreviousExecutableName) then",
    "    PreviousExecutableName := '';",
    "  PreviousInstallDir := GetPreviousData('InstallDir', '');",
    "  Result := True;",
    ...(options.webView2 === "check"
      ? [
          "  if not HasWebView2Runtime then begin",
          "    Log('WebView2 Runtime not detected; the app needs it at first run.');",
          "    if not WizardSilent then",
          "      MsgBox('Microsoft Edge WebView2 Runtime이 설치되어 있지 않습니다. 설치 후에도 앱이 첫 실행 시 필요합니다.', mbInformation, MB_OK);",
          "  end;",
        ]
      : []),
    "end;",
    "",
    "procedure RegisterPreviousData(PreviousDataKey: Integer);",
    "begin",
    `  SetPreviousData(PreviousDataKey, 'ExecutableName', '${executableLiteral}');`,
    "  SetPreviousData(PreviousDataKey, 'InstallDir', ExpandConstant('{app}'));",
    "end;",
    "",
  );
  return `${lines.join("\n")}\n`;
}

// Inno signs its embedded uninstaller and temporary setup copies through this
// callback. Credentials stay in the compiler's environment, never in .iss/JS
// files or Inno's logged command line. Verify each PE before embedding it.
export async function prepareInnoSigning(
  ctx: StageContext,
  staging: string,
  signtool: string,
) {
  const dir = join(staging, "inno-signing");
  const callback = join(dir, "sign.js");
  await mkdir(dir, {
    recursive: true,
  });
  await writeFile(
    callback,
    `try {
  const commands = JSON.parse(process.env.BUNAWAY_INNO_SIGN_COMMANDS);
  const file = process.argv[2];
  if (!file) throw new Error();
  for (const command of commands) {
    const result = Bun.spawnSync([...command, file], { stdout: "ignore", stderr: "ignore" });
    if (result.exitCode !== 0) throw new Error();
  }
} catch {
  console.error("Inno Authenticode signing or verification failed.");
  process.exit(1);
}
`,
  );
  const quote = (value: string) => `$q${value.replace(/\$/g, () => "$$")}$q`;
  return {
    args: [
      `/Sbunaway=${quote(process.execPath)} ${quote(callback)} $f`,
    ],
    env: {
      ...process.env,
      BUNAWAY_INNO_SIGN_COMMANDS: JSON.stringify([
        [
          signtool,
          "sign",
          ...signingArgs(ctx),
        ],
        [
          signtool,
          "verify",
          "/pa",
        ],
      ]),
    },
  };
}

// Writes the .iss and compiles it. Returns the produced installer path.
export async function compileInno(
  ctx: StageContext,
  iss: string,
  staging: string,
  outputBaseName: string,
): Promise<string> {
  const iscc = await findIscc();
  if (!iscc) {
    ctx.report({
      code: CODES.TOOL_MISSING,
      severity: "error",
      message:
        "Inno Setup compiler (ISCC.exe) not found; install Inno Setup 6.3 or newer.",
    });
    throw new Error("ISCC.exe not found.");
  }
  const issPath = join(staging, `${outputBaseName}.iss`);
  // BOM keeps Inno's Pascal parser happy with non-ASCII names.
  await writeFile(issPath, `﻿${iss}`);
  try {
    if (ctx.input.signing) {
      const signtool = await findWindowsKitTool("signtool.exe");
      if (!signtool) {
        throw new Error(
          "signtool.exe not found; cannot sign the embedded uninstaller.",
        );
      }
      const signing = await prepareInnoSigning(ctx, staging, signtool);
      await must(
        iscc,
        [
          "/Q",
          ...signing.args,
          issPath,
        ],
        {
          env: signing.env,
        },
      );
    } else {
      await must(iscc, [
        "/Q",
        issPath,
      ]);
    }
  } catch (error) {
    ctx.report({
      code: CODES.TOOL_FAILED,
      severity: "error",
      message: `Inno compile failed: ${error instanceof Error ? error.message : String(error)}`,
    });
    throw error;
  } finally {
    await rm(join(staging, "inno-signing"), {
      recursive: true,
      force: true,
    });
  }
  return join(staging, "installer", `${outputBaseName}.exe`);
}
