import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CODES, type StageContext } from "../../contract.ts";
import { findIscc, findWindowsKitTool, must, stableGuid } from "./common.ts";
import { signingArgs } from "./sign.ts";

// Inno Setup installer generation shared by win-direct and
// win-store-unpackaged. The script encodes the channel's install contract:
// install location by scope, WebView2 handling (check-only or bundled
// bootstrapper), shortcuts, per-user data preservation on uninstall, and
// over-install updates keyed by a stable AppId GUID.

export interface InnoOptions {
  name: string;
  identifier: string;
  version: string;
  publisher: string;
  scope: "perUser" | "perMachine";
  payloadDir: string;
  outputDir: string;
  outputBaseName: string;
  iconFile?: string;
  desktopShortcut: boolean;
  startMenuShortcut: boolean;
  webView2: "check" | "bootstrap";
  // Absolute path to Microsoft's Evergreen bootstrapper; only valid for
  // webView2="bootstrap". Store EXE/MSI submissions must be standalone and
  // never download at install time.
  bootstrapperPath?: string;
  // Absolute data root the host writes to; kept on uninstall unless the
  // channel config opts out (uninstall.preserveUserData=false).
  appDataDir: string;
  preserveUserData: boolean;
  signed?: boolean;
}

function issLiteral(value: string): string {
  if (/[\r\n\0]/.test(value)) throw new Error("Inno values must not contain line breaks or NUL.");
  return value.replace(/{/g, "{{");
}

function issParameter(value: string): string {
  return issLiteral(value).replace(/"/g, '""');
}

// Display names can contain characters forbidden in Windows directory names.
export function installerDirectoryName(name: string): string {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: Windows forbids these characters in file names.
  return name.replace(/[<>:"/\\|?*\x00-\x1f]/g, "_").replace(/[. ]+$/, "") || "App";
}

export function renderInnoScript(options: InnoOptions): string {
  const perUser = options.scope === "perUser";
  if (!perUser && !options.preserveUserData) {
    throw new Error(
      "perMachine installs must preserve user data; cleanup requires a perUser install.",
    );
  }
  const directoryName = issLiteral(installerDirectoryName(options.name));
  const identifier = issLiteral(options.identifier);
  const defaultDir = perUser
    ? `{localappdata}\\Programs\\${identifier}`
    : `{autopf}\\${identifier}`;
  const lines: string[] = [
    "; Generated by @bunaway/packaging — do not edit.",
    "[Setup]",
    `AppId={{${stableGuid(options.identifier)}}}`,
    `AppName=${issLiteral(options.name)}`,
    `AppVerName=${issLiteral(options.name)} ${options.version}`,
    `AppVersion=${options.version}`,
    `AppPublisher=${issLiteral(options.publisher)}`,
    `DefaultDirName=${defaultDir}`,
    `DefaultGroupName=${identifier}`,
    "WizardStyle=modern",
    "Compression=lzma2",
    "SolidCompression=yes",
    "ArchitecturesAllowed=x64compatible",
    "ArchitecturesInstallIn64BitMode=x64compatible",
    "CloseApplications=yes",
    "UninstallDisplayIcon={app}\\bunaway-host.exe",
    `OutputDir=${options.outputDir}`,
    `OutputBaseFilename=${options.outputBaseName}`,
    perUser ? "PrivilegesRequired=lowest" : "PrivilegesRequired=admin",
  ];
  if (options.signed) {
    lines.push(
      "SignTool=bunaway",
      "SignedUninstaller=yes",
      `SignedUninstallerDir=${join(options.outputDir, "..", "inno-signing")}`,
    );
  }
  if (options.iconFile) lines.push(`SetupIconFile=${options.iconFile}`);

  lines.push("", "[Files]");
  lines.push(
    `Source: "${options.payloadDir}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs`,
  );
  if (options.bootstrapperPath) {
    lines.push(
      `Source: "${issParameter(options.bootstrapperPath)}"; DestDir: "{tmp}"; DestName: "MicrosoftEdgeWebview2Setup.exe"; Flags: deleteafterinstall`,
    );
  }

  if (options.desktopShortcut) {
    lines.push(
      "",
      "[Tasks]",
      `Name: "desktopicon"; Description: "${issParameter(`${options.name} 바로가기 만들기`)}"; GroupDescription: "바로가기:"`,
    );
  }
  if (options.startMenuShortcut || options.desktopShortcut) {
    lines.push("", "[Icons]");
    if (options.startMenuShortcut) {
      lines.push(`Name: "{group}\\${directoryName}"; Filename: "{app}\\bunaway-host.exe"`);
      lines.push(`Name: "{group}\\${directoryName} 제거"; Filename: "{uninstallexe}"`);
    }
    if (options.desktopShortcut) {
      lines.push(
        `Name: "{autodesktop}\\${directoryName} (${identifier})"; Filename: "{app}\\bunaway-host.exe"; Tasks: desktopicon`,
      );
    }
  }

  const runEntries: string[] = [];
  if (options.bootstrapperPath) {
    runEntries.push(
      'Filename: "{tmp}\\MicrosoftEdgeWebview2Setup.exe"; Parameters: "/silent /install"; StatusMsg: "Installing Microsoft Edge WebView2 Runtime..."; Check: not HasWebView2Runtime; Flags: waituntilterminated',
    );
  }
  runEntries.push(
    `Filename: "{app}\\bunaway-host.exe"; Description: "${issParameter(`Launch ${options.name}`)}"; Flags: postinstall nowait skipifsilent unchecked`,
  );
  if (runEntries.length) lines.push("", "[Run]", ...runEntries);

  if (!options.preserveUserData) {
    lines.push("", "[UninstallDelete]", `Type: filesandordirs; Name: "${options.appDataDir}"`);
  }

  lines.push(
    "",
    "[Code]",
    "function HasRuntimeVersion(const Version: String): Boolean;",
    "var PackedVersion: Int64;",
    "begin",
    "  Result := False;",
    "  if StrToVersion(Version, PackedVersion) then",
    "    Result := ComparePackedVersion(PackedVersion, 0) > 0;",
    "end;",
    "",
    "// Evergreen WebView2 runtime presence check (Microsoft-documented GUID).",
    "function HasWebView2Runtime: Boolean;",
    "var Version: String;",
    "begin",
    "  Result := RegQueryStringValue(HKLM, 'SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
    "  if not Result then",
    "    Result := RegQueryStringValue(HKLM, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
    "  if not Result then",
    "    Result := RegQueryStringValue(HKCU, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and HasRuntimeVersion(Version);",
    "end;",
    "",
  );
  if (options.webView2 === "check") {
    lines.push(
      "function InitializeSetup: Boolean;",
      "begin",
      "  Result := True;",
      "  if not HasWebView2Runtime then begin",
      "    Log('WebView2 Runtime not detected; the app needs it at first run.');",
      "    if not WizardSilent then",
      "      MsgBox('Microsoft Edge WebView2 Runtime이 설치되어 있지 않습니다. 설치 후에도 앱이 첫 실행 시 필요합니다.', mbInformation, MB_OK);",
      "  end;",
      "end;",
      "",
    );
  }
  return `${lines.join("\n")}\n`;
}

// Inno signs its embedded uninstaller and temporary setup copies through this
// callback. Credentials stay in the compiler's environment, never in .iss/JS
// files or Inno's logged command line. Verify each PE before embedding it.
export async function prepareInnoSigning(ctx: StageContext, staging: string, signtool: string) {
  const dir = join(staging, "inno-signing");
  const callback = join(dir, "sign.js");
  await mkdir(dir, { recursive: true });
  await writeFile(
    callback,
    `try {
  const commands = JSON.parse(process.env.BUNAWAY_INNO_SIGN_COMMANDS);
  const file = process.argv[2];
  if (!file) throw new Error();
  for (const command of commands) {
    const result = Bun.spawnSync([...command, file], { stdout: "ignore", stderr: "ignore" });
    if (result.exitCode !== 0) throw new Error();
  }
} catch {
  console.error("Inno Authenticode signing or verification failed.");
  process.exit(1);
}
`,
  );
  const quote = (value: string) => `$q${value.replace(/\$/g, () => "$$")}$q`;
  return {
    args: [`/Sbunaway=${quote(process.execPath)} ${quote(callback)} $f`],
    env: {
      ...process.env,
      BUNAWAY_INNO_SIGN_COMMANDS: JSON.stringify([
        [signtool, "sign", ...signingArgs(ctx)],
        [signtool, "verify", "/pa"],
      ]),
    },
  };
}

// Writes the .iss and compiles it. Returns the produced installer path.
export async function compileInno(
  ctx: StageContext,
  iss: string,
  staging: string,
  outputBaseName: string,
): Promise<string> {
  const iscc = await findIscc();
  if (!iscc) {
    ctx.report({
      code: CODES.TOOL_MISSING,
      severity: "error",
      message: "Inno Setup compiler (ISCC.exe) not found; install Inno Setup 6.",
    });
    throw new Error("ISCC.exe not found.");
  }
  const issPath = join(staging, `${outputBaseName}.iss`);
  // BOM keeps Inno's Pascal parser happy with non-ASCII names.
  await writeFile(issPath, `﻿${iss}`);
  try {
    if (ctx.input.signing) {
      const signtool = await findWindowsKitTool("signtool.exe");
      if (!signtool)
        throw new Error("signtool.exe not found; cannot sign the embedded uninstaller.");
      const signing = await prepareInnoSigning(ctx, staging, signtool);
      await must(iscc, ["/Q", ...signing.args, issPath], { env: signing.env });
    } else {
      await must(iscc, ["/Q", issPath]);
    }
  } catch (error) {
    ctx.report({
      code: CODES.TOOL_FAILED,
      severity: "error",
      message: `Inno compile failed: ${error instanceof Error ? error.message : String(error)}`,
    });
    throw error;
  } finally {
    await rm(join(staging, "inno-signing"), { recursive: true, force: true });
  }
  return join(staging, "installer", `${outputBaseName}.exe`);
}
