import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CODES, type StageContext } from "../../contract.ts";
import { findIscc, must, stableGuid } from "./common.ts";

// Inno Setup installer generation shared by win-direct and
// win-store-unpackaged. The script encodes the channel's install contract:
// install location by scope, WebView2 handling (check-only or bundled
// bootstrapper), shortcuts, per-user data preservation on uninstall, and
// over-install updates keyed by a stable AppId GUID.

export interface InnoOptions {
  name: string;
  identifier: string;
  version: string;
  publisher: string;
  scope: "perUser" | "perMachine";
  payloadDir: string;
  outputDir: string;
  outputBaseName: string;
  iconFile?: string;
  desktopShortcut: boolean;
  startMenuShortcut: boolean;
  webView2: "check" | "bootstrap";
  // Absolute path to Microsoft's Evergreen bootstrapper; only valid for
  // webView2="bootstrap". Store EXE/MSI submissions must be standalone and
  // never download at install time.
  bootstrapperPath?: string;
  // Absolute data root the host writes to; kept on uninstall unless the
  // channel config opts out (uninstall.preserveUserData=false).
  appDataDir: string;
  preserveUserData: boolean;
}

function issEscape(value: string): string {
  return value.replace(/'/g, "''");
}

export function renderInnoScript(options: InnoOptions): string {
  const perUser = options.scope === "perUser";
  const defaultDir = perUser
    ? `{localappdata}\\Programs\\${options.name}`
    : `{autopf}\\${options.name}`;
  const lines: string[] = [
    "; Generated by @bunaway/packaging — do not edit.",
    "[Setup]",
    `AppId={{${stableGuid(options.identifier)}}}`,
    `AppName=${options.name}`,
    `AppVerName=${options.name} ${options.version}`,
    `AppVersion=${options.version}`,
    `AppPublisher=${options.publisher}`,
    `DefaultDirName=${defaultDir}`,
    `DefaultGroupName=${options.name}`,
    "WizardStyle=modern",
    "Compression=lzma2",
    "SolidCompression=yes",
    "ArchitecturesInstallIn64BitMode=x64compatible",
    "CloseApplications=yes",
    "UninstallDisplayIcon={app}\\bunaway-host.exe",
    `OutputDir=${options.outputDir}`,
    `OutputBaseFilename=${options.outputBaseName}`,
    perUser ? "PrivilegesRequired=lowest" : "PrivilegesRequired=admin",
  ];
  if (options.iconFile) lines.push(`SetupIconFile=${options.iconFile}`);

  lines.push("", "[Files]");
  lines.push(
    `Source: "${options.payloadDir}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs`,
  );
  if (options.bootstrapperPath) {
    lines.push(
      `Source: "${options.bootstrapperPath}"; DestDir: "{tmp}"; DestName: "MicrosoftEdgeWebview2Setup.exe"; Flags: deleteafterinstall`,
    );
  }

  if (options.desktopShortcut) {
    lines.push(
      "",
      "[Tasks]",
      `Name: "desktopicon"; Description: "${issEscape(`${options.name} 바로가기 만들기`)}"; GroupDescription: "바로가기:"`,
    );
  }
  if (options.startMenuShortcut || options.desktopShortcut) {
    lines.push("", "[Icons]");
    if (options.startMenuShortcut) {
      lines.push(`Name: "{group}\\${options.name}"; Filename: "{app}\\bunaway-host.exe"`);
      lines.push(
        `Name: "{group}\\${issEscape(`${options.name} 제거`)}"; Filename: "{uninstallexe}"`,
      );
    }
    if (options.desktopShortcut) {
      lines.push(
        `Name: "{autodesktop}\\${options.name}"; Filename: "{app}\\bunaway-host.exe"; Tasks: desktopicon`,
      );
    }
  }

  const runEntries: string[] = [];
  if (options.bootstrapperPath) {
    runEntries.push(
      'Filename: "{tmp}\\MicrosoftEdgeWebview2Setup.exe"; Parameters: "/silent /install"; StatusMsg: "Installing Microsoft Edge WebView2 Runtime..."; Check: not HasWebView2Runtime; Flags: waituntilterminated',
    );
  }
  runEntries.push(
    `Filename: "{app}\\bunaway-host.exe"; Description: "${issEscape(`Launch ${options.name}`)}"; Flags: postinstall nowait skipifsilent unchecked`,
  );
  if (runEntries.length) lines.push("", "[Run]", ...runEntries);

  if (!options.preserveUserData) {
    lines.push("", "[UninstallDelete]", `Type: filesandordirs; Name: "${options.appDataDir}"`);
  }

  lines.push(
    "",
    "[Code]",
    "// Evergreen WebView2 runtime presence check (Microsoft-documented GUID).",
    "function HasWebView2Runtime: Boolean;",
    "var Version: String;",
    "begin",
    "  Result := RegQueryStringValue(HKLM, 'SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and (Version <> '');",
    "  if not Result then",
    "    Result := RegQueryStringValue(HKLM, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and (Version <> '');",
    "  if not Result then",
    "    Result := RegQueryStringValue(HKCU, 'SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', 'pv', Version) and (Version <> '');",
    "end;",
    "",
  );
  if (options.webView2 === "check") {
    lines.push(
      "function InitializeSetup: Boolean;",
      "begin",
      "  Result := True;",
      "  if not HasWebView2Runtime then begin",
      "    Log('WebView2 Runtime not detected; the app needs it at first run.');",
      "    if not WizardSilent then",
      "      MsgBox('Microsoft Edge WebView2 Runtime이 설치되어 있지 않습니다. 설치 후에도 앱이 첫 실행 시 필요합니다.', mbInformation, MB_OK);",
      "  end;",
      "end;",
      "",
    );
  }
  return `${lines.join("\n")}\n`;
}

// Writes the .iss and compiles it. Returns the produced installer path.
export async function compileInno(
  ctx: StageContext,
  iss: string,
  staging: string,
  outputBaseName: string,
): Promise<string> {
  const iscc = await findIscc();
  if (!iscc) {
    ctx.report({
      code: CODES.TOOL_MISSING,
      severity: "error",
      message: "Inno Setup compiler (ISCC.exe) not found; install Inno Setup 6.",
    });
    throw new Error("ISCC.exe not found.");
  }
  const issPath = join(staging, `${outputBaseName}.iss`);
  // BOM keeps Inno's Pascal parser happy with non-ASCII names.
  await writeFile(issPath, `﻿${iss}`);
  try {
    await must(iscc, ["/Q", issPath]);
  } catch (error) {
    ctx.report({
      code: CODES.TOOL_FAILED,
      severity: "error",
      message: `Inno compile failed: ${error instanceof Error ? error.message : String(error)}`,
    });
    throw error;
  }
  return join(staging, "installer", `${outputBaseName}.exe`);
}
