import { parentPort, workerData } from "node:worker_threads";
import { type Core, type CoreSession, createCore } from "@bunaway/core";
import {
  BunawayError,
  type CancellationSignal,
  type HostContext,
  type HostResponse,
  PROTOCOL_VERSION,
} from "@bunaway/protocol";
import {
  Channel,
  type Packet,
  type Route,
} from "@bunaway/runtime-bun/worker-channel";
import type { MacosConfig } from "./config.ts";

const config: MacosConfig = workerData;
if (!parentPort) {
  throw new Error("macOS backend requires a Bun Worker.");
}
let core: Core | undefined;
let stopping = false;
let booting: Promise<Core> | undefined;
const sessions = new Map<
  string,
  {
    route: Route;
    session: CoreSession;
  }
>();
let sequence = 0;
const calls = new Map<
  string,
  {
    context: HostContext;
    signal: CancellationSignal;
    abort(): void;
    resolve(response: HostResponse): void;
    reject(error: unknown): void;
  }
>();
function takeCall(requestId: string) {
  const call = calls.get(requestId);
  if (call) {
    calls.delete(requestId);
    call.signal.removeEventListener("abort", call.abort);
  }
  return call;
}
let failed = false;
const fail = (error: unknown) => {
  if (failed) {
    return;
  }
  failed = true;
  console.error("macOS backend failed:", error);
  channel.notify({
    kind: "fatal",
    error: {
      code: "INTERNAL",
      message: "Backend failed.",
    },
  });
};
const channel = new Channel(
  parentPort,
  config.runtime,
  "macos-backend",
  async (packet: Packet) => {
    if (packet.kind === "host-response") {
      const pending = calls.get(packet.requestId);
      if (pending && pending.context !== packet.context) {
        throw new Error("Invalid host response context.");
      }
      takeCall(packet.requestId)?.resolve(packet.response);
      return;
    }
    if (packet.kind === "shutdown") {
      if (stopping) {
        return;
      }
      stopping = true;
      // Setup may await a Host response that shutdown will no longer deliver.
      for (const call of calls.values()) {
        call.abort();
      }
      // Return immediately so the Channel can acknowledge shutdown while cleanup
      // waits for setup and sends its own completion packet.
      void (async () => {
        core ??= await booting?.catch(() => undefined);
        await core?.stop();
        sessions.clear();
        await channel.send({
          kind: "cleaned",
        });
        await channel.drain();
        channel.close();
        parentPort?.close();
      })().catch(fail);
      return;
    }
    if (packet.kind === "revoke") {
      const session = sessions.get(packet.route.context);
      sessions.delete(packet.route.context);
      channel.discardServers(packet.route.context);
      await session?.session.close();
      return;
    }
    if (stopping) {
      return;
    }
    if (packet.kind === "session-open") {
      if (!core || sessions.has(packet.route.context)) {
        throw new Error("Invalid session-open.");
      }
      sessions.set(packet.route.context, {
        route: packet.route,
        session: core.openSession(packet.route.context, packet.route.viewId),
      });
    } else if (packet.kind === "client") {
      const session = sessions.get(packet.route.context);
      if (
        !session ||
        session.route.documentGeneration !== packet.route.documentGeneration ||
        session.route.viewId !== packet.route.viewId
      ) {
        throw new Error("Invalid client route.");
      }
      await session.session.receive(packet.message);
    } else {
      throw new Error("Unexpected macOS backend packet.");
    }
  },
  fail,
);

try {
  // @ts-expect-error app.js is generated by the framework bundler.
  const { default: imported } = await import("./app.js");
  const app: import("@bunaway/core").AppDefinition = imported;
  if (app.desktop !== undefined) {
    throw new BunawayError({
      code: "UNSUPPORTED",
      message: "macOS desktop lifecycle is not implemented.",
    });
  }
  const plugins = (app.plugins ?? []).flatMap((plugin) =>
    plugin.native
      ? [
          {
            name: plugin.name,
            version: plugin.version,
            native: plugin.native,
          },
        ]
      : [],
  );
  if (stopping) {
    parentPort.close();
  } else {
    booting = (async () => {
      await channel.send({
        kind: "native-register",
        plugins,
      });
      if (stopping) {
        throw new BunawayError({
          code: "CANCELLED",
          message: "Backend startup cancelled.",
        });
      }
      return createCore(app, {
        policy: config.policy,
        platform: "macos",
        backendContext: config.backendContext,
        hello: {
          kind: "hello",
          protocol: PROTOCOL_VERSION,
          features: [],
          buildId: config.runtime.id,
        },
        runtime: {
          createCancellation: () => new AbortController(),
          now: () => Date.now(),
          schedule(callback, delay) {
            const timer = setTimeout(callback, delay);
            return () => clearTimeout(timer);
          },
        },
        onCommandError(command, cause) {
          console.error(`Command ${command} failed:`, cause);
        },
        onPluginError(plugin, phase, cause) {
          console.error(`Plugin ${plugin} ${phase} failed:`, cause);
        },
        async send(context, message) {
          const session = sessions.get(context);
          if (session && !stopping) {
            await channel.send({
              kind: "server",
              route: session.route,
              message,
            });
          }
        },
        callHost: (context, call, signal) => {
          if (stopping || signal.aborted) {
            return Promise.reject(
              new BunawayError({
                code: "CANCELLED",
                message: "Host operation cancelled.",
              }),
            );
          }
          if (!channel.canSend(1, calls.size)) {
            return Promise.reject(
              new BunawayError({
                code: "BUSY",
                message: "Host request limit reached.",
              }),
            );
          }
          const requestId = `host-${++sequence}`;
          const source =
            context === config.backendContext
              ? "backend"
              : `view:${sessions.get(context)?.route.viewId ?? "invalid"}`;
          return new Promise<HostResponse>((resolve, reject) => {
            const abort = () => {
              if (!takeCall(requestId)) {
                return;
              }
              channel.notify({
                kind: "cancel",
                context,
                requestId,
              });
              reject(
                new BunawayError({
                  code: "CANCELLED",
                  message: "Host operation cancelled.",
                }),
              );
            };
            calls.set(requestId, {
              context,
              signal,
              abort,
              resolve,
              reject,
            });
            signal.addEventListener("abort", abort);
            void channel
              .send({
                kind: "operation",
                context,
                requestId,
                call,
                source,
              })
              .catch((error) => {
                takeCall(requestId)?.reject(error);
              });
          });
        },
      });
    })();
    core = await booting;
    if (!stopping) {
      await channel.send({
        kind: "ready",
      });
    }
  }
} catch (error) {
  if (
    !(stopping && error instanceof BunawayError && error.code === "CANCELLED")
  ) {
    fail(error);
  }
}
