import { parentPort, workerData } from "node:worker_threads";
import { createCore, type Core, type CoreSession } from "@bunaway/core";
import { BunawayError, PROTOCOL_VERSION } from "@bunaway/protocol";
import {
  Channel,
  type Packet,
  type Route,
} from "@bunaway/runtime-bun/worker-channel";
import type { MacosConfig } from "./config.ts";

const config: MacosConfig = workerData;
if (!parentPort) {
  throw new Error("macOS backend requires a Bun Worker.");
}
let core: Core | undefined;
let stopping = false;
let booting: Promise<Core> | undefined;
const sessions = new Map<
  string,
  {
    route: Route;
    session: CoreSession;
  }
>();
let failed = false;
const fail = (error: unknown) => {
  if (failed) {
    return;
  }
  failed = true;
  console.error("macOS backend failed:", error);
  channel.notify({
    kind: "fatal",
    error: {
      code: "INTERNAL",
      message: "Backend failed.",
    },
  });
};
const channel = new Channel(
  parentPort,
  config.runtime,
  "macos-backend",
  async (packet: Packet) => {
    if (packet.kind === "shutdown") {
      if (stopping) {
        return;
      }
      stopping = true;
      // Return immediately so the Channel can acknowledge shutdown while cleanup
      // waits for setup and sends its own completion packet.
      void (async () => {
        core ??= await booting?.catch(() => undefined);
        await core?.stop();
        sessions.clear();
        await channel.send({
          kind: "cleaned",
        });
        await channel.drain();
        channel.close();
        parentPort?.close();
      })().catch(fail);
      return;
    }
    if (packet.kind === "revoke") {
      const session = sessions.get(packet.route.context);
      sessions.delete(packet.route.context);
      channel.discardServers(packet.route.context);
      await session?.session.close();
      return;
    }
    if (stopping) {
      return;
    }
    if (packet.kind === "session-open") {
      if (!core || sessions.has(packet.route.context)) {
        throw new Error("Invalid session-open.");
      }
      sessions.set(packet.route.context, {
        route: packet.route,
        session: core.openSession(packet.route.context, packet.route.viewId),
      });
    } else if (packet.kind === "client") {
      const session = sessions.get(packet.route.context);
      if (
        !session ||
        session.route.documentGeneration !== packet.route.documentGeneration ||
        session.route.viewId !== packet.route.viewId
      ) {
        throw new Error("Invalid client route.");
      }
      await session.session.receive(packet.message);
    } else {
      throw new Error("Unexpected macOS backend packet.");
    }
  },
  fail,
);

try {
  // @ts-expect-error app.js is generated by the framework bundler.
  const { default: app } = await import("./app.js");
  if (app.desktop !== undefined) {
    throw new BunawayError({
      code: "UNSUPPORTED",
      message: "macOS desktop lifecycle is not implemented.",
    });
  }
  if (stopping) {
    parentPort.close();
  } else {
    booting = createCore(app, {
      policy: config.policy,
      platform: "macos",
      backendContext: config.backendContext,
      hello: {
        kind: "hello",
        protocol: PROTOCOL_VERSION,
        features: [],
        buildId: config.runtime.id,
      },
      runtime: {
        createCancellation: () => new AbortController(),
        now: () => Date.now(),
        schedule(callback, delay) {
          const timer = setTimeout(callback, delay);
          return () => clearTimeout(timer);
        },
      },
      onCommandError(command, cause) {
        console.error(`Command ${command} failed:`, cause);
      },
      onPluginError(plugin, phase, cause) {
        console.error(`Plugin ${plugin} ${phase} failed:`, cause);
      },
      async send(context, message) {
        const session = sessions.get(context);
        if (session && !stopping) {
          await channel.send({
            kind: "server",
            route: session.route,
            message,
          });
        }
      },
      callHost: async () => {
        throw new BunawayError({
          code: "UNSUPPORTED",
          message: "macOS native plugin adapters are not implemented.",
        });
      },
    });
    core = await booting;
    if (!stopping) {
      await channel.send({
        kind: "ready",
      });
    }
  }
} catch (error) {
  fail(error);
}
